# Generated by Django 5.2.7 on 2025-10-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('wishlist', 'Wishlist')], default='wishlist', max_length=20)),
                ('episodes_watched', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('review', models.TextField(blank=True)),
            ],
        ),
    ]
