# Generated by Django 5.2.7 on 2025-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='episodes_watched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Wishlist'), ('watching', 'Watching'), ('completed', 'Completed')], default='wishlist', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_episodes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
